Organisationstool/Controllers/Organisator/O-MitwirkendeController.cs
using Microsoft.AspNetCore.Mvc;
using Organisationstool.Data;
using Organisationstool.Models;
using Microsoft.AspNetCore.Authorization;
using Organisationstool.Utility;
using Organisationstool.Data.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using Organisationstool.Models.ViewModels;

namespace Organisationstool.Controllers.Admin
{
    
    public class O_MitwirkendeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public O_MitwirkendeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {

            List<Mitwirkende> objMitwirkenderList = _unitOfWork.Mitwirkender.GetAll(includeProperties: "Veranstaltung").ToList();

            return View(objMitwirkenderList);
        }
        public IActionResult Upsert(int? id)
        {

            MitwirkenderVM MitwirkenderVM = new()
            {

                VeranstaltungList = _unitOfWork.Veranstaltungen.GetAll().Select(u => new SelectListItem
                {
                    Text = u.NamederVeranstaltung,
                    Value = u.Id.ToString()
                }),
                Mitwirkende = new Mitwirkende()
            };
            if (id == null || id == 0)
            {
                //create
                return View(MitwirkenderVM);
            }
            else
            {
                //update
                MitwirkenderVM.Mitwirkende = _unitOfWork.Mitwirkender.Get(u => u.Id == id);
                return View(MitwirkenderVM);
            }
        }
        [HttpPost]
        public IActionResult Upsert(MitwirkenderVM MitwirkenderVM)
        {

            if (ModelState.IsValid)
            {
                if (MitwirkenderVM.Mitwirkende.Id == 0)
                {

                    if (MitwirkenderVM.Mitwirkende.VeranstaltungId == 0)
                    {
                        TempData["error"] = "Veranstaltung muss gefüllt sein";
                        return View(MitwirkenderVM);
                    }
                    else
                    {
                        _unitOfWork.Mitwirkender.Add(MitwirkenderVM.Mitwirkende);
                        TempData["success"] = "Mitwirkende erfolgreich hinzugefügt";
                    }

                }
                else
                {
                    if (MitwirkenderVM.Mitwirkende.VeranstaltungId == 0)
                    {
                        TempData["error"] = "Veranstaltung muss gefüllt sein";
                        return View(MitwirkenderVM);
                    }
                    else
                    {
                        _unitOfWork.Mitwirkender.Update(MitwirkenderVM.Mitwirkende);
                        TempData["success"] = "Mitwirkende erfolgreich bearbeitet";
                    }

                }


                _unitOfWork.Save();


                return RedirectToAction("Index");

            }

            return View(MitwirkenderVM);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Mitwirkende> objMitwirkenderList = _unitOfWork.Mitwirkender.GetAll(includeProperties: "Veranstaltung").ToList();
            return Json(new { data = objMitwirkenderList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var MitwirkenderToBeDeleted = _unitOfWork.Mitwirkender.Get(u => u.Id == id);
            if (MitwirkenderToBeDeleted == null)
            {
                return Json(new { success = false, message = "Fehler beim löschen" });
            }

            _unitOfWork.Mitwirkender.Remove(MitwirkenderToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Mitwirkende erfolgreich gelöscht" });
        }

        #endregion

    }
}

Organisationstool/Views/O_Mitwirkende/Index.cshtml
@model List<Mitwirkende>


<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Mitwirkende Liste</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="O_Mitwirkende" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>  Neuen Mitwirkenden hinzufügen
                </a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Aufgabe</th>
                    <th>Essen</th>
                    <th>Allergie</th>
                    <th>Veranstaltung</th>
                    <th></th>
                </tr>
            </thead>
        </table>

    </div>
</div>

@section Scripts{
    <script src="~/js/mitwirkendero12.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.11.3/i18n/German.json"></script>
}

Organisationstool/Views/O_Mitwirkende/Upsert.cshtml
@model MitwirkenderVM

@{

    List<SelectListItem> l1 = new List<SelectListItem>();
    l1.Add(new SelectListItem() { Text = "Keine", Value = "Keine" });
    l1.Add(new SelectListItem() { Text = "Fleisch", Value = "Fleisch" });
    l1.Add(new SelectListItem() { Text = "Vegan", Value = "Vegan" });
    l1.Add(new SelectListItem() { Text = "Vegetarian", Value = "Vegetarian" });

}
<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> @(Model.Mitwirkende.Id != 0 ? "Mitwirkende bearbeiten" : "Neuen Mitwirkenden hinzufügen") </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Mitwirkende.Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        @*<div asp-validation-summary="ModelOnly"></div>*@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Mitwirkende.Name" class="form-control border-0 shadow" />
                            <label asp-for="Mitwirkende.Name" class="ms-2"></label>
                            <span asp-validation-for="Mitwirkende.Name" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="Mitwirkende.Email" class="form-control border-0 shadow" />
                            <label asp-for="Mitwirkende.Email" class="ms-2"></label>
                            <span asp-validation-for="Mitwirkende.Email" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Mitwirkende.Aufgaben" class="form-control border-0 shadow" />
                            <label asp-for="Mitwirkende.Aufgaben" class="ms-2"></label>
                            <span asp-validation-for="Mitwirkende.Aufgaben" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <select asp-for="Mitwirkende.Essen" asp-items="@l1" class="form-select border-0 shadow">
                                <label asp-for="Mitwirkende.Essen" class="ms-2">Essen</label>
                                <option disabled selected>--Essen Auswählen--</option>
                            </select>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Mitwirkende.Allergien" class="form-control border-0 shadow" />
                            <label asp-for="Mitwirkende.Allergien" class="ms-2"></label>
                            <span asp-validation-for="Mitwirkende.Allergien" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <select asp-for="@Model.Mitwirkende.VeranstaltungId" asp-items="@Model.VeranstaltungList" class="form-select border-0 shadow">
                                <option disabled selected>--Veranstaltung--</option>
                            </select>
                            <label asp-for="Mitwirkende.VeranstaltungId" class="ms-2">Veranstaltung</label>
                            <span asp-validation-for="Mitwirkende.VeranstaltungId" class="text-danger"></span>
                        </div>



                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Mitwirkende.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Aktualisieren</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Einfügen</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="O_Mitwirkende" asp-action="Index" class="btn btn-outline-primary border  form-control">
                                    Zurück
                                </a>
                            </div>
                        </div>


                    </div>
                </div>

            </div>

        </form>
    </div>
</div>