Organisationstool/Controllers/Organisator/O-VeranstaltungController.cs
using Microsoft.AspNetCore.Mvc;
using Organisationstool.Data;
using Organisationstool.Models;
using Microsoft.AspNetCore.Authorization;
using Organisationstool.Utility;
using Organisationstool.Data.Repository.IRepository;
using Octokit;

namespace Organisationstool.Models.Controllers.Admin
{
    [Authorize(Roles = SD.Role_Org)]
    public class O_VeranstaltungController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public O_VeranstaltungController(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;

        }
        public IActionResult Index()
        {
            List<Veranstaltungen> objVeranstaltungList = _unitOfWork.Veranstaltungen.GetAll().ToList();
            return View(objVeranstaltungList);
        }
        public IActionResult Upsert(int? id)
        {

            if (id == null || id == 0)
            {
                //create
                return View(new Veranstaltungen());
            }
            else
            {
                //update
                Veranstaltungen? veranstaltungfromDb = _unitOfWork.Veranstaltungen.Get(u => u.Id == id);
                if (veranstaltungfromDb == null)
                {
                    return NotFound();
                }
                return View(veranstaltungfromDb);

            }
        }
        [HttpPost]
        public IActionResult Upsert(Veranstaltungen obj)
        {

            if (ModelState.IsValid)
            {

                if (obj.Id == 0)
                {
                    SaveBild(obj);
                    _unitOfWork.Veranstaltungen.Add(obj);
                    TempData["success"] = "Veranstaltung erfolgreich erstellt";
                }
                else
                {

                    _unitOfWork.Veranstaltungen.Update(obj);
                    TempData["success"] = "Veranstaltung erfolgreich bearbeitet";
                }
                SaveBild(obj);
                _unitOfWork.Save();
               
                return RedirectToAction("Index");
            }
            else
            {

                return View(obj);
            }
        }
        private void SaveBild(Veranstaltungen obj)
        {
            if (obj.BildStream != null && obj.BildStream.Length > 0)
            {
                var uploadFolder = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads");
                var filename = obj.BildStream.FileName;
                var filePath = Path.Combine(uploadFolder, filename);
                using (var stream = new FileStream(filePath, System.IO.FileMode.Create))
                {
                    obj.BildStream.CopyTo(stream);
                }
            }
        }
        public IActionResult Deletehaupt(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Veranstaltungen? veranstaltungfromDb = _unitOfWork.Veranstaltungen.Get(u => u.Id == id);
            if (veranstaltungfromDb == null)
            {
                return NotFound();
            }
            return View(veranstaltungfromDb);
        }
        [HttpPost, ActionName("Deletehaupt")]
        public IActionResult DeletePOST(int? id)
        {
            Veranstaltungen? obj = _unitOfWork.Veranstaltungen.Get(u => u.Id == id);
            if (id == null || id == 0)
            {
                return NotFound();
            }
            _unitOfWork.Veranstaltungen.Remove(obj!);
            _unitOfWork.Save();
            TempData["success"] = "Veranstaltung erfolgreich gelöscht";
            return RedirectToAction("Index");

        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Veranstaltungen> objVeranstaltungList = _unitOfWork.Veranstaltungen.GetAll().ToList();
            return Json(new { data = objVeranstaltungList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var VeranstaltungenToBeDeleted = _unitOfWork.Veranstaltungen.Get(u => u.Id == id);
            if (VeranstaltungenToBeDeleted == null)
            {
                return Json(new { success = false, message = "Fehler beim löschen" });
            }

            _unitOfWork.Veranstaltungen.Remove(VeranstaltungenToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Veranstaltung erfolgreich gelöscht" });
        }

        #endregion

    }
}

Organisationstool/Views/O_Veranstaltung/Deletehaupt.cshtml
@model Veranstaltungen
<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Veranstaltung Löschen</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>

        </div>

        <form method="post">
            <input asp-for="Id" hidden />
            <div class="border p-3 mt-4">
               
                <div class="mb-3 row p-1">
                    <label class="p-0">Name Veranstaltung</label>
                    <input asp-for="NamederVeranstaltung" type="text" disabled class="form-control" />
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Adresse</label>
                    <input asp-for="Adresse" type="text" disabled class="form-control" />
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Nr.Gäste</label>
                    <input asp-for="Nrgäste" type="text" disabled class="form-control" />

                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0"> Nr.Mitwirkende</label>
                    <input asp-for="NrMit" type="text" disabled class="form-control" />

                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Budget € </label>
                    <input asp-for="Budget" type="text" disabled class="form-control" />

                   

                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Datum & Uhrzeit</label>
                    <input asp-for="Datum" type="text" disabled class="form-control" />
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Bemerkung</label>
                    <input asp-for="Bemerkung" type="text" disabled class="form-control" />
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Essen Auswählen</label>

                    <input asp-for="Essen" type="text" disabled class="form-control" />

                </div>

                <div class="mb-3 row p-1">
                    <label class="p-0">Bild</label>
                    <input asp-for="Bild" type="text" disabled class="form-control" />
                </div>




                <div class="row">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Löschen</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="O_Veranstaltung" asp-action="Index" class="btn btn-warning border  form-control">
                            Zurück
                        </a>
                    </div>



                </div>
            </div>
        </form>

    </div>
</div>

Organisationstool/Views/O_Veranstaltung/Index.cshtml
@model List< Veranstaltungen>
<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Veranstaltungen Liste</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="O_Veranstaltung" asp-action="Upsert" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i>  Neue Veranstaltung erstellen
                </a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered table-striped start-0" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Adresse</th>
                    <th>Gäste</th>
                    <th>Mitwirkenden</th>
                    <th>Budget€</th>
                    <th>Aufgaben</th>
                    <th>Essen</th>
                    <th>Bild</th>

                    <th></th>
                </tr>
            </thead>
        </table>

    </div>
</div>

@section Scripts{
    <script src="~/js/veranstaltungor123.js"></script>
    <script src="https://cdn.datatables.net/plug-ins/1.11.3/i18n/German.json"></script>
}

Organisationstool/Views/O_Veranstaltung/Upsert.cshtml
@model Veranstaltungen
@{
   
    List<SelectListItem> l1 = new List<SelectListItem>();
    l1.Add(new SelectListItem() { Text = "Alles verfügbar", Value = "Alles verfügbar" });
    l1.Add(new SelectListItem() { Text = "Fleisch", Value = "Fleisch" });
    l1.Add(new SelectListItem() { Text = "Vegan", Value = "Vegan" });
    l1.Add(new SelectListItem() { Text = "Vegetarian", Value = "Vegetarian" });
}
<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> @(Model.Id != 0 ? "Veranstaltung bearbeiten" : "Neue Veranstaltung erstellen") </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />
            <div class="row">
                <div class="col-12">
                    <div class="border p-3">
                        @*<div asp-validation-summary="ModelOnly"></div>*@
                        <div class="form-floating py-2 col-12">
                            <input asp-for="NamederVeranstaltung" class="form-control border-0 shadow" />
                            <label asp-for="NamederVeranstaltung" class="ms-2"></label>
                            <span asp-validation-for="NamederVeranstaltung" class="text-danger"></span>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input asp-for="Adresse" class="form-control border-0 shadow" />
                            <label asp-for="Adresse" class="ms-2"></label>
                            <span asp-validation-for="Adresse" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Datum" type="datetime-local" class="form-control border-0 shadow" />
                            <label asp-for="Datum" class="ms-2">Datum & Uhrzeit</label>
                            <span asp-validation-for="Datum" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <select asp-for="Essen" asp-items="@l1" class="form-select border-0 shadow">
                                <option disabled selected>--Essen Auswählen--</option>
                            </select>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Nrgäste" class="form-control border-0 shadow" />
                            <label asp-for="Nrgäste" class="ms-2">Anzahl Gäste</label>
                            <span asp-validation-for="Nrgäste" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="NrMit" class="form-control border-0 shadow" />
                            <label asp-for="NrMit" class="ms-2">Anzahl Mitwirkende</label>
                            <span asp-validation-for="NrMit" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Bemerkung" class="form-control border-0 shadow" />
                            <label asp-for="Bemerkung" class="ms-2"></label>
                            <span asp-validation-for="Bemerkung" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Budget" class="form-control border-0 shadow" />
                            <label asp-for="Budget" class="ms-2"></label>
                            <span asp-validation-for="Budget" class="text-danger"></span>
                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Aufgaben" class="form-control border-0 shadow" />
                            <label asp-for="Aufgaben" class="ms-2"></label>
                            <span asp-validation-for="Aufgaben" class="text-danger"></span>
                        </div>
                        <div class="mb-3 row p-1">
                            <label class="p-0">Bild</label>
                            <input asp-for="Bild" readonly type="text" class="form-control" id="Bild" />
                            <span asp-validation-for="BildStream" class="text-danger"></span>
                            <input asp-for="BildStream" type="file" class="form-control" id="BildStream" />
                        </div>


                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Aktualisieren</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Einfügen</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="O_Veranstaltung" asp-action="Index" class="btn btn-outline-primary border  form-control">
                                    Zurück
                                </a>
                            </div>
                        </div>


                    </div>
                </div>

            </div>

        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $("#BildStream").change(function () {
            var filename = $(this).val().split("\\").pop();
            $("#Bild").val(filename);
        });
    });
</script>

@*<div class="card shadow border-0 mt-4">
    <div class="card-header bg-light bg-dark m-lg-0 py-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="py-2 text-white">Neue Veranstaltung erstellen</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" enctype="multipart/form-data">
            <div class="border p-3 mt-4">
               
                <div class="mb-3 row p-1">
                    <label class="p-0">Name der Veranstaltung</label>
                    <input asp-for="NamederVeranstaltung" type="text" class="form-control" />
                    <span asp-validation-for="NamederVeranstaltung" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Adresse</label>
                    <input asp-for="Adresse" type="text" class="form-control" />
                    <span asp-validation-for="Adresse" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Nr.Gäste</label>
                    <input asp-for="Nrgäste" type="text" class="form-control" />
                    <span asp-validation-for="Nrgäste" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0"> Nr.Mitwirkende</label>
                    <input asp-for="NrMit" type="text" class="form-control" />
                    <span asp-validation-for="NrMit" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Budget € </label>
                    <input asp-for="Budget" type="text" class="form-control" />
                    <span asp-validation-for="Budget" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Datum & Uhrzeit</label>
                    <input asp-for="Datum" type="datetime-local" class="form-control" />
                    <span asp-validation-for="Datum" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Details</label>
                    <input asp-for="Bemerkung" type="text" class="form-control" />
                    <span asp-validation-for="Bemerkung" class="text-danger"></span>
                </div>
                <div class="mb-3 row p-1">
                    <label class="p-0">Essen Auswahl</label>
                    <select asp-for="Essen" asp-items="@l1" class="form-select">
                        <option disabled selected>Essen Auswahl</option>
                    </select>
                </div>


                <div class="mb-3 row p-1">
                    <label class="p-0">Bild</label>
                    <input asp-for="Bild" readonly type="text" class="form-control" id="Bild" />
                    <span asp-validation-for="Bild" class="text-danger"></span>
                    <input asp-for="BildStream" type="file" class="form-control" id="BildStream" />
                </div>

            </div>


            <div class="row">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-primary form-control">Einfügen</button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="A_Veranstaltung" asp-action="Index" class="btn btn-warning border  form-control">
                        Zurück
                    </a>
                </div>



            </div>
        </form>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $("#BildStream").change(function () {
            var filename = $(this).val().split("\\").pop();
            $("#Bild").val(filename);
        });
    });
</script>*@