Organisationstool/Controllers/Admin/A-GastController.cs
using Microsoft.AspNetCore.Mvc;
using Organisationstool.Data;
using Microsoft.AspNetCore.Authorization;
using Organisationstool.Utility;
using Organisationstool.Data.Repository.IRepository;
using Nest;
using Microsoft.AspNetCore.Mvc.Rendering;
using Organisationstool.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using System.Data;

namespace Organisationstool.Models.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class AGastController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
       
        public AGastController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Gast> objGastList = _unitOfWork.Gast.GetAll(includeProperties: "Veranstaltung").ToList();
           
            return View(objGastList);
        }
        public IActionResult Upsert(int? id)
        {
           
            GastVM GastVM = new()
            {
                 
                VeranstaltungList = _unitOfWork.Veranstaltungen.GetAll().Select(u => new SelectListItem
                {
                    Text = u.NamederVeranstaltung,
                    Value = u.Id.ToString()
                }),
              
                Gast = new Gast()
             
            };
          
            if (id == null || id == 0)
            {
               
                //create
                return View(GastVM);
            }
            else
            {
                //update
                GastVM.Gast = _unitOfWork.Gast.Get(u => u.Id == id);
                return View(GastVM);
            }
        }
        [HttpPost]
        public IActionResult Upsert(GastVM GastVM)
        {

            if (ModelState.IsValid)
            {

                if (GastVM.Gast.Id == 0)
                {

                    if (GastVM.Gast.VeranstaltungId == 0)
                    {
                        TempData["error"] = "Veranstaltung muss gefüllt sein";
                        return View(GastVM);
                    }
                    else
                    {
                        _unitOfWork.Gast.Add(GastVM.Gast);
                        TempData["success"] = "Gast erfolgreich hinzugefügt";
                    }

                }
                else
                {
                    if (GastVM.Gast.VeranstaltungId == 0)
                    {
                        TempData["error"] = "Veranstaltung muss gefüllt sein";
                        return View(GastVM);
                    }
                    else
                    {
                        _unitOfWork.Gast.Update(GastVM.Gast);
                        TempData["success"] = "Gast erfolgreich bearbeitet";
                    }
                }
                    _unitOfWork.Save();

              
                return RedirectToAction("Index");

            }
           
            return View(GastVM);
        }
       
        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Gast> objGastList = _unitOfWork.Gast.GetAll(includeProperties: "Veranstaltung").ToList();
            return Json(new { data = objGastList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var GastToBeDeleted = _unitOfWork.Gast.Get(u => u.Id == id);
            if (GastToBeDeleted == null)
            {
                return Json(new { success = false, message = "Fehler beim löschen" });
            }

            _unitOfWork.Gast.Remove(GastToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Gast erfolgreich gelöscht" });
        }

        #endregion

    }




}

Organisationstool/Controllers/Admin/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Organisationstool.Data;
using Organisationstool.Models;
using Microsoft.AspNetCore.Authorization;
using Organisationstool.Utility;
using Microsoft.AspNetCore.Mvc.Rendering;
using Organisationstool.Data.Repository.IRepository;
using Microsoft.Extensions.Hosting.Internal;

namespace Organisationstool.Models.Controllers.Admin
{

    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;

        }
        public IActionResult Index()
        {
            List<Product> objVeranstaltungenList = _unitOfWork.Products.GetAll().ToList();
            return View(objVeranstaltungenList);
        }



        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Product? veranstaltungfromDb = _unitOfWork.Products.Get(u => u.Id == id);
            if (veranstaltungfromDb == null)
            {
                return NotFound();
            }
            return View(veranstaltungfromDb);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Product obj)
        {
            if (ModelState.IsValid)
            {
                SaveBild(obj);
                _unitOfWork.Products.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Produkt erfolgreich erstellt";
                return RedirectToAction("Index");
            }
            return View();
        }
        private void SaveBild(Product obj)
        {
            if (obj.BildStream != null && obj.BildStream.Length > 0)
            {
                var uploadFolder = Path.Combine(_hostingEnvironment.WebRootPath, "Uploads");
                var filename = obj.BildStream.FileName;
                var filePath = Path.Combine(uploadFolder, filename);
                using (var stream = new FileStream(filePath, System.IO.FileMode.Create))
                {
                    obj.BildStream.CopyTo(stream);
                }
            }
        }
        [HttpPost]
        public IActionResult Edit(Product obj)
        {
            if (ModelState.IsValid)
            {
                EditProductPriceCart(obj);
                SaveBild(obj);
                _unitOfWork.Products.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Produkt erfolgreich bearbeitet";
                return RedirectToAction("Index");
            }
            return View();
        }

        private void EditProductPriceCart(Product obj)
        {
            Cart cart = GetCartFromSession();
            var products = cart.Products.Where(_ => _.Id == obj.Id);
            foreach (var product in products)
            {
                product.Price = obj.Price;
            }
            SaveCartToSession(cart);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Product? veranstaltungfromDb = _unitOfWork.Products.Get(u => u.Id == id);
            if (veranstaltungfromDb == null)
            {
                return NotFound();
            }
            return View(veranstaltungfromDb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Product? obj = _unitOfWork.Products.Get(u => u.Id == id);
            if (id == null || id == 0)
            {
                return NotFound();
            }
            RemoveProductCart(obj!);
            _unitOfWork.Products.Remove(obj!);
            _unitOfWork.Save();
            TempData["success"] = "Produkt erfolgreich gelöscht";
            return RedirectToAction("Index");

        }

        private void RemoveProductCart(Product obj)
        {
            Cart cart = GetCartFromSession();
            var productsToRemove = cart.Products.Where(_ => _.Id == obj.Id).ToList();
            foreach (var productToRemove in productsToRemove)
            {
                cart.Products.Remove(productToRemove);
            }

            SaveCartToSession(cart);
        }

        public IActionResult AddToCart(int id)
        {
            Product product = _unitOfWork.Products.Get(u => u.Id == id);
            if (product != null)
            {
                Cart cart = GetCartFromSession();
                cart.Products.Add(product);
                SaveCartToSession(cart);
            }
            TempData["success"] = "Zum Einkaufswagen hinzugefügt";
            return RedirectToAction("Index");
        }

        // Aktion zum Anzeigen des Einkaufswagens
        public IActionResult Cart()
        {
            Cart cart = GetCartFromSession();
            var veranstaltungen = _unitOfWork.Veranstaltungen.GetAll().ToList();
            cart.VeranstaltungenListItems = veranstaltungen.Select(_ => new SelectListItem { Value = _.Id.ToString(), Text = _.NamederVeranstaltung }).ToList();
            return View(cart);
        }

        public IActionResult BudgetBerechnen(int VeranstaltungId)
        {
            Cart cart = GetCartFromSession();
            var veranstaltung = _unitOfWork.Veranstaltungen.Get(_ => _.Id == VeranstaltungId);
            cart.Budget = veranstaltung?.Budget;
            cart.VeranstaltungId = VeranstaltungId;
            SaveCartToSession(cart);
            return RedirectToAction("Cart", cart);
        }

        public IActionResult DeleteFromCart(int id)
        {
            Cart cart = GetCartFromSession();
            var product = cart.Products.Find(_ => _.Id == id);
            TempData["success"] = "Produkt erfolgreich gelöscht";
            cart.Products.Remove(product);
            SaveCartToSession(cart);
            return RedirectToAction("Cart", cart);
        }

        private Cart GetCartFromSession()
        {
            Cart cart = HttpContext.Session.GetObject<Cart>("Cart");
            if (cart == null)
            {
                cart = new Cart();
                SaveCartToSession(cart);
            }
            return cart;
        }

        private void SaveCartToSession(Cart cart)
        {
            HttpContext.Session.SetObject("Cart", cart);
        }
    }
}

Organisationstool/Controllers/Admin/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Organisationstool.Data;
using Organisationstool.Models;
using Microsoft.AspNetCore.Authorization;
using Organisationstool.Utility;
using Organisationstool.Models.Controllers.Admin;
using Organisationstool.Data.Repository;
using Organisationstool.Data.Repository.IRepository;


namespace Organisationstool.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<ApplicationUser> objOrganisatorList = _unitOfWork.ApplicationUser.GetAll().ToList();
            return View(objOrganisatorList);
        }
        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> objOrganisatorList = _unitOfWork.ApplicationUser.GetAll().ToList();
            return Json(new { data = objOrganisatorList });
        }

        #endregion

    }
}

Organisationstool/Controllers/Organisator/O-GastController.cs
using Microsoft.AspNetCore.Mvc;
using Organisationstool.Data;
using Microsoft.AspNetCore.Authorization;
using Organisationstool.Utility;
using Organisationstool.Data.Repository.IRepository;
using Microsoft.AspNetCore.Mvc.Rendering;
using Organisationstool.Models.ViewModels;

namespace Organisationstool.Models.Controllers
{
    [Authorize(Roles = SD.Role_Org)]
    public class OGastController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public OGastController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Gast> objGastList = _unitOfWork.Gast.GetAll(includeProperties: "Veranstaltung").ToList();

            return View(objGastList);
        }
        public IActionResult Upsert(int? id)
        {

            GastVM GastVM = new()
            {

                VeranstaltungList = _unitOfWork.Veranstaltungen.GetAll().Select(u => new SelectListItem
                {
                    Text = u.NamederVeranstaltung,
                    Value = u.Id.ToString()
                }),

                Gast = new Gast()

            };

            if (id == null || id == 0)
            {

                //create
                return View(GastVM);
            }
            else
            {
                //update
                GastVM.Gast = _unitOfWork.Gast.Get(u => u.Id == id);
                return View(GastVM);
            }
        }
        [HttpPost]
        public IActionResult Upsert(GastVM GastVM)
        {

            if (ModelState.IsValid)
            {

                if (GastVM.Gast.Id == 0)
                {

                    if (GastVM.Gast.VeranstaltungId == 0)
                    {
                        TempData["error"] = "Veranstaltung muss gefüllt sein";
                        return View(GastVM);
                    }
                    else
                    {
                        _unitOfWork.Gast.Add(GastVM.Gast);
                        TempData["success"] = "Gast erfolgreich hinzugefügt";
                    }

                }
                else
                {
                    if (GastVM.Gast.VeranstaltungId == 0)
                    {
                        TempData["error"] = "Veranstaltung muss gefüllt sein";
                        return View(GastVM);
                    }
                    else
                    {
                        _unitOfWork.Gast.Update(GastVM.Gast);
                        TempData["success"] = "Gast erfolgreich bearbeitet";
                    }
                }
                _unitOfWork.Save();


                return RedirectToAction("Index");

            }

            return View(GastVM);
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            List<Gast> objGastList = _unitOfWork.Gast.GetAll(includeProperties: "Veranstaltung").ToList();
            return Json(new { data = objGastList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var GastToBeDeleted = _unitOfWork.Gast.Get(u => u.Id == id);
            if (GastToBeDeleted == null)
            {
                return Json(new { success = false, message = "Fehler beim löschen" });
            }

            _unitOfWork.Gast.Remove(GastToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Gast erfolgreich gelöscht" });
        }

        #endregion

    }


}

Organisationstool/Views/Shared/_Layout.cshtml
@using Organisationstool.Utility;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Organisationstool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Organisationstool.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Home" asp-action="Index">Hauptseite</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="A_Veranstaltung" asp-action="Index">Veranstaltungen</a>
                            </li>
                            <li class="nav-item  dropdown">
                                <a  class="nav-link  dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Rolle
                                </a>
                                <ul class="dropdown-menu ">
                                    <li class="nav-item ">
                                        <a class="dropdown-item " asp-controller="AOrganisator" asp-action="Index">Organisatoren</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item"  asp-controller="A_Mitwirkende" asp-action="Index">Mitwirkenden</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item"  asp-controller="AGast" asp-action="Index">Gäste</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="User" asp-action="Index">Rollen anzeigen</a>
                                    </li>
                                </ul>
                            </li>
                           
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Produkt
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Product" asp-action="Index">Produkten</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Product" asp-action="Cart">Einkaufswagen</a>
                                    </li>
                                </ul>
                            </li>
                            
                        }
                        @if (User.IsInRole(SD.Role_Org))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="O_Veranstaltung" asp-action="Index">Veranstaltungen</a>
                            </li>
                            <li class="nav-item  dropdown">
                                <a class="nav-link  dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Rolle
                                </a>
                                <ul class="dropdown-menu ">
                                   
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="O_Mitwirkende" asp-action="Index">Mitwirkenden</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="OGast" asp-action="Index">Gäste</a>
                                   
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Produkt
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Product" asp-action="Index">Produkten</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-controller="Product" asp-action="Cart">Einkaufswagen</a>
                                    </li>
                                </ul>
                            </li>
                          
                        }
                        @if (User.IsInRole(SD.Role_Mitw))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="M_Aufgaben" asp-action="Index">Aufgaben</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="T_Buchen" asp-action="list">Meine Buchungen</a>
                            </li>
                           

                        }
                        @if (User.IsInRole(SD.Role_User))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="T_Buchen" asp-action="list">Meine Buchungen</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifiction" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="text-center">
            EventManager   <i class="bi bi-calendar4-week"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/plug-ins/1.13.5/i18n/de-DE.json" ></script>
  
   
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Organisationstool/Views/Shared/_Notifiction.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}